2024-03-31 16:59:57,228 ERROR: Exception on /login [GET] [in /home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/driiisdev/dev/microblog/app/routes/login.py", line 23, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/driiisdev/dev/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/driiisdev/dev/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block 'body'
    {% block navbar %}
  File "/home/driiisdev/dev/microblog/app/templates/base.html", line 21, in block 'navbar'
    <a class="navbar-brand" href="{{ url_for('/index') }}">Microblog</a>
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1074, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1063, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint '/index'. Did you mean 'index' instead?
2024-03-31 17:01:38,311 INFO: Microblog startup [in /home/driiisdev/dev/microblog/app/__init__.py:40]
2024-03-31 17:01:42,896 ERROR: Exception on /login [GET] [in /home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/driiisdev/dev/microblog/app/routes/login.py", line 23, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/driiisdev/dev/microblog/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/driiisdev/dev/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block 'body'
    {% block navbar %}
  File "/home/driiisdev/dev/microblog/app/templates/base.html", line 25, in block 'navbar'
    <li><a href="{{ url_for('index') }}">{{ _('Home') }}</a></li>
  File "/home/driiisdev/dev/microblog/venv/lib/python3.10/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: '_' is undefined
